<style type="text/css">
.form_table dt, .form_table dd {
float: left;
line-height: 25px;
}
.form_table dt {
width: 140px;
text-align: right;
padding-right: 15px;
white-space: nowrap;
color: #666;
}
.form_table dd{
word-wrap: break-word;
width: 260px;
}
.op_title{
height: 29px;
overflow: hidden;
border-top: 1px solid #e2e2e2;
padding: 0 5px 0 10px;
line-height: 29px;
}
.op_title span{
  font-size: 14px;
  font-weight: 700;
  vertical-align: middle;
}
.op_title .fl{
float: left;
}
.op_title .fr{
	float: right;
}
.notice_warn{
  position: absolute;
  margin-top: -5px;
  display: inline;
}

</style>
<?php $this->jQuery();?>
<div id="showZone" >
  <div class="op_title">
	<div class="fl">
	  <span >应用基本信息</span>
	</div>
	<div class="fr"><a href="javascript:edit();" class="op_title_btn"><span>编辑</span></a></div>
  </div>
  <div class="form_table">
	<dl class="clearfix" >
	  <dt>应用名称：</dt><dd><?php echo $client['client_name'] ?></dd>
	</dl>
	<dl class="clearfix" >
	  <dt>应用类型：</dt><dd><?php echo $client['client_name'] ?></dd>
	</dl>
	<dl class="clearfix">
	  <dt>App Key：</dt><dd><?php echo $client['client_id'] ?></dd>
	</dl>
	<dl class="clearfix">
	  <dt>App Secret：</dt><dd><?php echo $client['client_secret'] ?></dd>
	</dl>
	<dl class="clearfix">
	  <dt>创建时间：</dt><dd><?php echo $client['time_create'] ?></dd>
	</dl>
	<dl class="clearfix">
	  <dt>应用地址：</dt><dd><?php echo $client['redirect_uri'] ?></dd>
	</dl>
	<dl class="clearfix">
	  <dt>应用介绍：</dt><dd><?php echo $client['client_desc'] ?></dd>
	</dl>
  </div>
</div>

<div id="editZone" style="display:none">
  <div class="op_title">
	<div class="fl"><span>应用基本信息</span></div>
  </div>
  <div class="form_table">
	<dl class="clearfix">
	  <dt>应用名称：</dt><dd><input id="client_name" type="text" name="client_name" value="<?php echo $client['client_name'] ?>" ></dd>
	  <dd><div class="notice_warn">该名称也用于来源显示，不超过10个汉字或20个字母</div></dd>
	</dl>
	<dl class="clearfix">
	  <dt>App Key：</dt><dd >807623131</dd>
	</dl>
	<dl class="clearfix">
	  <dt>App Secret：</dt><dd>ffe0196047f079c929f1c0eb62be72a9</dd>
	</dl>
	
	<dl class="clearfix">
	<dt>应用地址：</dt><dd><input id="redirect_uri" type="text" name="redirect_uri" value="http://github.com/lele11"></dd>
	  <dd><div class="notice_warn">授权过程的回调地址必须在该域名地址下</div>
	  </dd>
	</dl>
	<dl class="clearfix">
	  <dt>应用介绍：</dt><dd><textarea id="client_desc" name="client_desc" >无法直接使用 使用基本的网络技术 是信安这些</textarea></dd>
	  <dd><div class="notice_warn">简述应用的作用、使用方法等信息，将显示在应用广场中，不超过1000汉字</div></dd>
	</dl>
	<dl class="clearfix">
	  <dt>创建时间：</dt><dd>2013-05-13</dd>
	</dl>
	<dl class="clearfix">
	  <dt> &nsp</dt>
	  <dd >
		<button onclick="save()">保存</button><button onclick="cancle()">取消</button>
	  </dd>
	</dl>
  </div>
</div>



<script type="text/javascript">
function save(){
    var name = document.getElementById("client_name").value;
    var redirect = document.getElementById("redirect_uri").value;
    var desc = document.getElementById("client_desc").value;
    console.log({client_name : name, redirect_uri : redirect, client_desc : desc});
    $.ajax({url:"oauth/client/updateinfo",type:"POST",data:{client_name : name, redirect_uri : redirect, client_desc : desc},async:false,success: function(){}});
    // $.post("oauth/client/updateinfo", {client_name : name, redirect_uri : redirect, client_desc : desc}, function(data){
    //     // if (1 === data) {

    //     // }
    //     // if ()
    // });
}
function cancle()
{
	document.getElementById('editZone').style.display="none";
	document.getElementById('showZone').style.display="";
}
function edit()
{
	document.getElementById('showZone').style.display="none";
	document.getElementById('editZone').style.display="";
}
</script>